// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHhZrKNVgIAHu2AewDzQtJxbFYmNjfhQ',
    appId: '1:850598099884:web:60b11895987dfda2431809',
    messagingSenderId: '850598099884',
    projectId: 'my-movie-list-app-6775b',
    authDomain: 'my-movie-list-app-6775b.firebaseapp.com',
    storageBucket: 'my-movie-list-app-6775b.firebasestorage.app',
    measurementId: 'G-5ZR9T93B9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8P4lQZdhA-1JlMHxlWJ0VMzeUSmZA8Fk',
    appId: '1:850598099884:android:4f024a0d8e4517a6431809',
    messagingSenderId: '850598099884',
    projectId: 'my-movie-list-app-6775b',
    storageBucket: 'my-movie-list-app-6775b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBED5xTdHA-Lh_aQ1XW-FPZXboeujgq50o',
    appId: '1:850598099884:ios:8172b70386ccd97e431809',
    messagingSenderId: '850598099884',
    projectId: 'my-movie-list-app-6775b',
    storageBucket: 'my-movie-list-app-6775b.firebasestorage.app',
    iosBundleId: 'com.example.myMovieList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBED5xTdHA-Lh_aQ1XW-FPZXboeujgq50o',
    appId: '1:850598099884:ios:8172b70386ccd97e431809',
    messagingSenderId: '850598099884',
    projectId: 'my-movie-list-app-6775b',
    storageBucket: 'my-movie-list-app-6775b.firebasestorage.app',
    iosBundleId: 'com.example.myMovieList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQHhZrKNVgIAHu2AewDzQtJxbFYmNjfhQ',
    appId: '1:850598099884:web:858e4438ef3ae6b5431809',
    messagingSenderId: '850598099884',
    projectId: 'my-movie-list-app-6775b',
    authDomain: 'my-movie-list-app-6775b.firebaseapp.com',
    storageBucket: 'my-movie-list-app-6775b.firebasestorage.app',
    measurementId: 'G-0ZYN9EH4RE',
  );
}
